# syntax for this file https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions
# help on github actions: https://docs.github.com/en/actions/learn-github-actions/introduction-to-github-actions
name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  run_tests:
    runs-on: ubuntu-latest
    container:
      runs-on: ubuntu-latest
      image: nicksinas/gnu-gcc-arm-none-eabi
      steps:
        - uses: actions/checkout@v2
        - name: Build the container
          run: docker build -t gcc-arm .
        - name: Run the container
          run: docker run -it gcc-arm
        - name: Run the unit tests in the container
          run: ceedling