# syntax for this file https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions
# help on github actions: https://docs.github.com/en/actions/learn-github-actions/introduction-to-github-actions
name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build_and_test:
    runs-on: ubuntu-latest
    container:
      image: nicksinas/gnu-gcc-arm-none-eabi
    steps:
      - uses: actions/checkout@v2
      - name: Checkout submodules
        run: git submodule update --init --recursive
      - name: Make PCA10056
        run: make -C src/uart/pca10056/blank/armgcc
      - name: Make PCA10040
        run: make -C src/uart/pca10040/blank/armgcc
      - name: Run the unit tests in the container
        run: ceedling